# Generated by Django 4.1.5 on 2023-01-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('zipcode', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'address',
                'ordering': ['pk'],
            },
        ),
    ]
